version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: "14.2.0"
    steps:
      - checkout
      - node/install-packages
      - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
